### ISSUE TITLE
Kinda Need Help

### ISSUE THREAD

**Issue by hellboss300** [VoronFX/Aurora#2]
Well Im using ur CPU Load / GPU Load Scripts but the issue is i have a logitech G810 keyboard not a logitech g910 so the GPU Load was made for the G Keys on the side and i dont have them on my G810 anyway to rebind their keys to any keys visible to me on my G810?

**Comment by VoronFX** [comment]
Sure, you can rebind them inside script file. There are DeviceKeys.G1, DeviceKeys.G2 and so on. 
Or you can wait for a new version that coming in a 2-3 days or a week at most. There will be support for new Aurora version and graphical interface for keys and other script settings.

**Comment by elemated** [comment]
Will you update the readme when your update is finished? Or how will we know it's completed? Thanks!

**Comment by VoronFX** [comment]
Sure. I will update readme, post comment on YouTube and reply to this thread. Be sure you will not miss it.)
I've just finished one important improvement in Aurora. So now I can update the scripts. Coming soon, be patient )

**Comment by hellboss300** [comment]
Cant wait :D

**Comment by hellboss300** [comment]
Any new updates?

**Comment by VoronFX** [comment]
Guess what I have here? A new, fresh and tasty, just baked scripts!!! Check them out! [vscripts-v1.0-beta.7](https://github.com/VoronFX/Aurora/releases/tag/vscripts-v1.0-beta.7)

Sorry for delay. Be sure I am also was sitting without my own scripts while developing new version. And in my case I can't just use old version, cause I am developing new ones.
There was a big changes in Aurora. Firstly I spent a lot of time redesign input capturing system of Aurora to remove input lags it was causing. After that I could just upgrade scripts to work with new version, but Aurora added an ability to create GUI for scripts. I wanted to integrate my scripts in Aurora long time ago and almost made it, but didn't complete. Now I got chance to get most of what I wanted to get by integrating. So I decided to use it and it took a lot of time. It's still not an integration but a nice compromise. Will be a nice middle step if I will manage to complete full integration sometime.

Anyway, All this is past now. A new scripts are ready! Check them out and let me know what you think. =)

**Comment by elemated** [comment]
@voronFX Wow, thank you for your hard work! I can't wait to try it out. I'll be sure to give you any feedback I have. What a great project!

**Comment by VoronFX** [comment]
Oh, I've just re uploaded them with small fix without changing version, I was sure nobody have downloaded them in this 2 hours. Pls, re download ).

**Comment by icexuick** [comment]
Tried It and it works like a charm!! Awesome Work with the ping flash. Very convenient to monitor my server's uptime. CPU and GPU load also work perfectly.

**Comment by hellboss300** [comment]
Cant seem to get it appear in Aurora even tho i put it in the correct folder.. (i guess so atleast)

**Comment by icexuick** [comment]
I have another small problem - settings don't get saved right.
Maybe this is a Auror Dev 2.1 problem, but i can't delete shortcuts f.e., they remain in the settings.
And when saving to a new profile, the settings don't get saved, instead a default profile is saved.

**Comment by VoronFX** [comment]
Not fully understand which settings are not saved and how. Do you mean settings of script layer?
I know one bug which causes settings to be shared across several just created script layers, so if you change one, this changes are reflected on all previous layers. But it solves with restarting Aurora, after you create layers and restarted, setting are no longer shared and every layer can be configured.
Don't know if we talking about the same bug. Anyway try latest Aurora I've just built and using.
[Aurora_ffc2e06.zip](https://github.com/VoronFX/Aurora/files/1225944/Aurora_ffc2e06.zip)

**Comment by icexuick** [comment]
Maybe it was the same bug, not sure, *but your new version fixed it!*
I can now remove shortcuts i added, which i wanted deleted.
With the previous version this was not possible.

Awesome work! Keep pushing this into the world.
It's a bit unfortunate Aurora is pretty hard to find, and also your
profile(s), and how to install them with the scripts, needed some degree of
nerdy-ness.
I certainly know people who are very interested in your work, but don't
have the knowhow how to install it.
The new settings from within Aurora are great, which everybody, including
the less geeky-people, can use with ease.

Met vriendelijke groet,

*Martijn Hoppenbrouwer*
<http://www.ixstudios.nl>
[image: iX Studios | Website] <https://www.ixstudios.nl>
telefoon  0541 - 530 532 <0541%20530%20532>
mobiel  06 - 4181 3329


2017-08-15 20:16 GMT+02:00 VoronFX <notifications@github.com>:

**Comment by VoronFX** [comment]
Thank you for feedback! I am glad your problem is fixed now!
You are right about that Aurora is not easy to find, even I after I've seen it and forget the name spent a lot of time to find it again. 
As for my scripts I've tried to post info about theme on every related resource, don't know what else I can do. Also I provided instructions everywhere. Installation is quiet simple, just copy to directory. A lot of people are able to handle some cracks and patches that are much harder to install usually. I think they should handle copying to directory, Nevertheless you are right, sadly there are still people that has problems with this.
Probably the only thing I can do is to merge scripts in Aurora itself as I was planning before. I hope someday I will find a time and wish to accomplish this. 

Also I believe that fact of buying such keyboard already makes you a geek, a bit =)

**Comment by icexuick** [comment]
Its a very powerfull piece of software, so i think/hope that this will
'surface' on the internet eventually.
But maybe there should be a large section on the site
http://aurora.modworkshop.net/ about the install of custom profiles &
scripts.
It mostly simple Q&A and it otherwise directs to github, which to a lot of
people will be complicated.

Maybe some more youtube coverage? That's were i found you.

*Good luck, anyways.*

Hopefully also the support for games can be more stable.
I was triggered by the Rocket League implementation, but i read (later on)
that this is too much work.
I think it's fair to state this on the site http://aurora.modworkshop.net/
(that this currently does not work - because that was a big downer for me -
first thing i tried did not work..)

I'm not sure if you're the same author of the Aurora Software (but it seems
that way).
If so, you might want to consider the above.

Met vriendelijke groet,

*Martijn Hoppenbrouwer*
<http://www.ixstudios.nl>
[image: iX Studios | Website] <https://www.ixstudios.nl>
telefoon  0541 - 530 532
mobiel  06 - 4181 3329


2017-08-16 11:41 GMT+02:00 Igor Voronin <notifications@github.com>:

**Comment by VoronFX** [comment]
> I'm not sure if you're the same author of the Aurora Software (but it seems
> that way).

No, I am not the author. @antonpup is. But he no longer works on it. Now main contributor is @simon-wh.
I am just made scripts and contributing sometimes. 

There are indeed a lot of things inside Aurora and outside(like inaccurate description that you mentioned) that needs a cleanup or improvement, but there is simply no time for doing this. Maybe someday... =)
